# Generated by Django 4.1.3 on 2022-11-29 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_directmessage_date_groupmessage_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directmessage',
            name='date',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='groupmessage',
            name='date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
