# Generated by Django 4.1.3 on 2022-12-01 13:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_alter_directmessage_date_alter_groupmessage_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="directmessage",
            name="wait_time",
            field=models.IntegerField(
                default=20,
                validators=[
                    django.core.validators.MaxValueValidator(100),
                    django.core.validators.MinValueValidator(15),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="groupmessage",
            name="wait_time",
            field=models.IntegerField(
                default=20,
                validators=[
                    django.core.validators.MaxValueValidator(100),
                    django.core.validators.MinValueValidator(15),
                ],
            ),
        ),
    ]
