# Generated by Django 4.1.3 on 2022-12-02 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_directmessage_interval_groupmessage_interval"),
    ]

    operations = [
        migrations.AddField(
            model_name="directmessage",
            name="interval_period",
            field=models.CharField(
                blank=True,
                choices=[("hour", "Hour"), ("minute", "Minute"), ("day", "Day")],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="groupmessage",
            name="interval_period",
            field=models.CharField(
                blank=True,
                choices=[("hour", "Hour"), ("minute", "Minute"), ("day", "Day")],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="directmessage",
            name="interval",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="groupmessage",
            name="interval",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
