# Generated by Django 4.1.3 on 2022-12-03 18:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("django_celery_beat", "0016_alter_crontabschedule_timezone"),
        ("main", "0009_directmessage_interval_period_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="directmessage",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[("Active", "Active"), ("Disabled", "Disabled")],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="directmessage",
            name="task",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="django_celery_beat.periodictask",
            ),
        ),
        migrations.AddField(
            model_name="groupmessage",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[("Active", "Active"), ("Disabled", "Disabled")],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="groupmessage",
            name="task",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="django_celery_beat.periodictask",
            ),
        ),
        migrations.AlterField(
            model_name="directmessage",
            name="date",
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name="directmessage",
            name="interval_period",
            field=models.CharField(
                blank=True,
                choices=[("hours", "Hour"), ("minutes", "Minute"), ("days", "Day")],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="groupmessage",
            name="date",
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name="groupmessage",
            name="interval_period",
            field=models.CharField(
                blank=True,
                choices=[("hours", "Hour"), ("minutes", "Minute"), ("days", "Day")],
                max_length=100,
                null=True,
            ),
        ),
    ]
