# Generated by Django 4.1.3 on 2022-12-06 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0010_directmessage_status_directmessage_task_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="directmessage",
            name="close_time",
            field=models.IntegerField(blank=True, default=3, null=True),
        ),
        migrations.AlterField(
            model_name="groupmessage",
            name="close_time",
            field=models.IntegerField(blank=True, default=3, null=True),
        ),
    ]
