# Generated by Django 4.1.3 on 2022-12-06 19:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0011_alter_directmessage_close_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="directmessage",
            name="wait_time",
            field=models.IntegerField(
                default=20,
                validators=[
                    django.core.validators.MaxValueValidator(100),
                    django.core.validators.MinValueValidator(15),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="groupmessage",
            name="wait_time",
            field=models.IntegerField(
                default=20,
                validators=[
                    django.core.validators.MaxValueValidator(100),
                    django.core.validators.MinValueValidator(15),
                ],
            ),
        ),
    ]
