# Generated by Django 4.1.3 on 2022-12-08 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0012_alter_directmessage_wait_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="directmessage",
            name="one_off",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="groupmessage",
            name="one_off",
            field=models.BooleanField(default=False),
        ),
    ]
