# Generated by Django 4.1.3 on 2022-12-08 22:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0013_directmessage_one_off_groupmessage_one_off"),
    ]

    operations = [
        migrations.AlterField(
            model_name="directmessage",
            name="wait_time",
            field=models.IntegerField(
                blank=True,
                default=20,
                validators=[
                    django.core.validators.MaxValueValidator(100),
                    django.core.validators.MinValueValidator(15),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="groupmessage",
            name="wait_time",
            field=models.IntegerField(
                blank=True,
                default=20,
                validators=[
                    django.core.validators.MaxValueValidator(100),
                    django.core.validators.MinValueValidator(15),
                ],
            ),
        ),
    ]
