# Generated by Django 4.1.3 on 2022-12-09 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0016_alter_directmessage_one_off_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="directmessage",
            name="close_time",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="groupmessage",
            name="close_time",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
